### PR TITLE
Typo

### PR DESCRIPTION
**Pull request by a-aros**
This is a PR for commenting on recent review (+ some typo/grammar fixes)

### CODE REVIEW

**Comment by a-aros** [comment]
@jcramer Can you please clarify how the:

 `bfp_msg_type = 0x02`: An off-chain file referenced via a URI.

... is intended to be used?  In particular, does this mean the file **must** be off-chain?    Do we permit it to be **on-chain** as well like `bfp_msg_type = 0x01`?  I could not find it in the document where it comments on whether it is optional/allowable to also have a fully on-chain file, but leveraging an off-chain second layer for distribution.

I'll think about this and write back here on ideas for this point

**Comment by jcramer** [comment]
On-chain files (bfp_msg_type 0x01) have an optional field `file_uri_utf8` which can be used to allow downloads directly from off-chain source instead of on-chain source.

I suppose we could delete bfp_msg_type 0x02 and just have msg type 0x01 `chunk_count` set to 0 to indicate there is no data for the file stored on-chain.  Do you agree with removing 0x02 entirely?

**Comment by a-aros** [comment]
Thanks for clarifying, I completely missed the `file_uri_utf8` in my review and just assumed it was moved to 0x02.

I like the purity of having just an on-chain representation, but when I worked through what the new message format worked like, then it appeared like it would be an unnecessary extra message the same format basically.

The idea of setting `chunk_count` to 0 to indicate this seems like it is adequate.  One ambiguity is for the user agent to know what to do if the `chunk_count` is 0 -> Whether they should use the `chunk_X_data_bytes` (if fully content in the single transaction) or whether to look to the `file_uri_utf8`

But I don't think it is a problem because the client can use the following logic to determine where the content is:

```
# If chunk_count is 0, then this can be either an off-chain file or an on-chain file
# The following logic will allow the user agent to determine which scenario it is dealing with
if chunk_count == 0
    if chunk_X_data_bytes != NULL
        # The entire file is content in the metadata transaction
        return chunk_X_data_bytes
    elsif file_uri_utf8 != NULL
        # The file is stored only off-chain at the uri
        # ... (Use off-chain specific storage device access)
        return read(file_uri_utf8)
    else
        # There is no content in the transaction and there is no file_uri_utf8
        # Then this is simply the "empty" file, which is valid
        return NULL
    end
end

```

@jcramer To answer your question, I think there is value in allowing users to publish 'file records' without it being on-chain.  For example, we may have just pointers to files on Torrents or IPFS for example.  **To serve this use case we do not need to have bfp_msg_type 0x02 and can safely drop it since `chunk_count` is adequate**

**Comment by a-aros** [comment]
@jcramer Would like to make these changes, or shall I go ahead and do so? I will be able to complete another review and edits later today for these points. Thanks

**Comment by jcramer** [comment]
OK. I can remove the type 0x02 message after this PR is merged.  

Yes having an immutable pointer also holding some metadata about the off-chain file could definitely have value, especially if the off-chain storage device does not have a hash based URI like IPFS does.  We both agree this can be done with message 0x01 by setting chunk_count to 0.

The only question I have left is I don't see what typo you are referring to. In your commit, all I see is two spaces removed.  Am I missing something?

**Comment by a-aros** [comment]
@jcramer Agreed!

Rebased, pushed with the typo fix now (Dat -> Data). The spaces are removed automatically by the IDE,  I can turn off that setting if you prefer for the future.

**Pull request merged**
